3d_viewer:

  window:
    name: "3D Viewer"
    width: 1240
    height: 720
    render_pyramid: false
    render_trajectory: true
    resizable: true
    render_hz: 60
    camera_velocity: 0.01
    camera_x: 0.06213385
    camera_y: 0.00921031
    camera_z: 0.00284838

  rgb_image:
    rgb_image_width: 640
    rgb_image_height: 480
    rgb_image_topic: "/camera/color/image_raw"

  point_cloud:
    width: 640
    height: 576
    size_multiplier: 2
    point_size: 3
    hfov: 75
    vfov: 65
    point_cloud_topic: "/camera/depth_registered/points" 
  
trajectory:
  trajectory_points_topic: "/trajectory_points"
  dummy_trajectory: true

  
