ros2_topic_list:
  /power/battery_level,/String
  /power/is_charging,/String
  /power/is_docked,/String
  /power/is_emergency,/String
  /power/is_plugged,/Bool
  /power/time_emergency,/Bool
  /power_board,/Bool
  /power_status,/Bool
  /camera/depth_registered/points,/PointCloud2