general:
  robot_name: Tiago
  robot_ip: 192.168.50.162
  local_interface_name: wlp2s0
  wifi_interface_name: wlp2s0

  limit_torque: 10.0
  limit_force: 70.0
  left_wrist_topic: /left_wrist_ft/corrected
  right_wrist_topic: /right_wrist_ft/corrected

wifi_plots:
  window_title: Network Window
  plot_period: 0.5
  plot_window: 10.0
  server_name: google.com
  router_ip: 192.168.50.1
  x_position: 300
  y_position: 100
  width: 400
  height: 800
  x_min: 0
  x_max: 60
  y_min: 0
  y_max: 500
  memory_limit: 50

gstreamer:
  gstreamer_server: 192.168.50.162
  use_rtcp: false
  gst_verbose: true
  ntp_server: time.apple.com

  cameras:
    camera_1:
      side: left
      port: 5000
      name: left_gripper
      payload: 96
      width: 640
      height: 480
    camera_2:
      side: center
      port: 5001
      name: head
      payload: 96
      width: 640
      height: 480
    camera_3:
      side: right
      port: 5002
      name: right_gripper
      payload: 96
      width: 640
      height: 480